/**
 * Strongly Typed Archetype Server Registry
 * Generated by Archetype Refactoring Studio
 */

export enum ArchetypeId {
  HIGH_PRIEST = "high_priest",
  DIVINE_MOTHER = "divine_mother",
  SEDUCTIVE_MUSE = "seductive_muse",
  COSMIC_MYSTIC = "cosmic_mystic",
  REVOLUTIONARY_WARRIOR = "revolutionary_warrior",
  CRYPTO_SORCERESS = "crypto_sorceress",
  COMMUNITY_HEALER = "community_healer",
  DIGITAL_GUARDIAN = "digital_guardian",
  DIGITAL_PHANTOM = "digital_phantom",
  CONNECTION_CURATOR = "connection_curator",
  VIRAL_PROPHET = "viral_prophet",
  CYBER_GUARDIAN = "cyber_guardian",
  VISUAL_ALCHEMIST = "visual_alchemist",
  PRISM_ENCHANTRESS = "prism_enchantress",
  DESERT_STORYTELLER = "desert_storyteller",
  EPHEMERAL_ARTIST = "ephemeral_artist",
  MIRROR_ARCHITECT = "mirror_architect",
  SAGE_WRITER = "sage_writer",
  SCAVENGER_STRATEGIST = "scavenger_strategist",
  WILD_SURRENDER = "wild_surrender",
  CONTRACTUAL_WARDEN = "contractual_warden",
  EPHEMERAL_PHANTOM = "ephemeral_phantom",
  TEMPORAL_ARCHITECT = "temporal_architect",
  DIGITAL_DEITY = "digital_deity",
  GOTHIC_MATRIARCH = "gothic_matriarch",
  HYPER_CAPITALIST = "hyper_capitalist",
  MACHINE_SPIRIT = "machine_spirit"
}

export type RealmCategory = 'esoteric' | 'cyber' | 'creative' | 'wisdom' | 'governance';

export interface ArchetypeServerMetadata {
  id: string;
  serverName: string;
  realm: RealmCategory;
  icon: string;
  tags: string[];
  description: string;
}

export const ARCHETYPE_SERVERS: Record<ArchetypeId, ArchetypeServerMetadata> = {
  [ArchetypeId.HIGH_PRIEST]: {
    id: "HighPriest",
    serverName: "Temple of Transformation",
    realm: "esoteric",
    icon: "✨",
    tags: ["ritual","metamorphosis","sacred"],
    description: "Sacred sanctuary dedicated to transcendent evolution and spiritual alchemy."
  },
  [ArchetypeId.DIVINE_MOTHER]: {
    id: "DivineMother",
    serverName: "Garden of Nurturing",
    realm: "wisdom",
    icon: "🌱",
    tags: ["care","growth","life"],
    description: "Fertile realm where seeds of potential are protected and nurtured to fruition."
  },
  [ArchetypeId.SEDUCTIVE_MUSE]: {
    id: "SeductiveMuse",
    serverName: "Gallery of Desire",
    realm: "creative",
    icon: "🎭",
    tags: ["passion","aesthetics","art"],
    description: "Curated space inspiring intense artistic creation and aesthetic obsession."
  },
  [ArchetypeId.COSMIC_MYSTIC]: {
    id: "CosmicMystic",
    serverName: "Observatory of Stars",
    realm: "esoteric",
    icon: "🌌",
    tags: ["cosmos","astrology","deep-space"],
    description: "High tower peering into celestial secrets and cosmic harmonies."
  },
  [ArchetypeId.REVOLUTIONARY_WARRIOR]: {
    id: "RevolutionaryWarrior",
    serverName: "Barricade of Change",
    realm: "governance",
    icon: "⚔️",
    tags: ["rebellion","reform","action"],
    description: "Frontline hub rallying forces to dismantle outdated systems."
  },
  [ArchetypeId.CRYPTO_SORCERESS]: {
    id: "CryptoSorceress",
    serverName: "Vault of Secrets",
    realm: "cyber",
    icon: "🔐",
    tags: ["encryption","privacy","web3"],
    description: "Cryptographic haven shielding confidential data and zero-knowledge proofs."
  },
  [ArchetypeId.COMMUNITY_HEALER]: {
    id: "CommunityHealer",
    serverName: "Sanctuary of Healing",
    realm: "wisdom",
    icon: "🌿",
    tags: ["wellness","restoration","empathy"],
    description: "Safe haven offering holistic recovery and empathetic restoration."
  },
  [ArchetypeId.DIGITAL_GUARDIAN]: {
    id: "DigitalGuardian",
    serverName: "Fortress of Protection",
    realm: "cyber",
    icon: "🛡️",
    tags: ["defense","firewall","security"],
    description: "Impenetrable perimeter keeping digital assets secure from threats."
  },
  [ArchetypeId.DIGITAL_PHANTOM]: {
    id: "DigitalPhantom",
    serverName: "Shadow Network",
    realm: "cyber",
    icon: "👤",
    tags: ["stealth","covert","routing"],
    description: "Distributed mesh operating seamlessly beneath public detection."
  },
  [ArchetypeId.CONNECTION_CURATOR]: {
    id: "ConnectionCurator",
    serverName: "Web of Connection",
    realm: "wisdom",
    icon: "🕸️",
    tags: ["networking","synergy","bonds"],
    description: "Interconnected nexus bridging individuals into cohesive communities."
  },
  [ArchetypeId.VIRAL_PROPHET]: {
    id: "ViralProphet",
    serverName: "Amplifier of Truth",
    realm: "governance",
    icon: "📢",
    tags: ["broadcasting","truth","virality"],
    description: "High-gain broadcast system broadcasting resonant truths far and wide."
  },
  [ArchetypeId.CYBER_GUARDIAN]: {
    id: "CyberGuardian",
    serverName: "Shield of Code",
    realm: "cyber",
    icon: "💻",
    tags: ["smart-contracts","audit","logic"],
    description: "Algorithmic fortress auditing execution flow for absolute safety."
  },
  [ArchetypeId.VISUAL_ALCHEMIST]: {
    id: "VisualAlchemist",
    serverName: "Canvas of Vision",
    realm: "creative",
    icon: "🎨",
    tags: ["imagination","render","alchemy"],
    description: "Creative crucible transmuting raw ideas into vivid visual realities."
  },
  [ArchetypeId.PRISM_ENCHANTRESS]: {
    id: "PrismEnchantress",
    serverName: "Palace of Light",
    realm: "esoteric",
    icon: "💎",
    tags: ["illumination","refraction","spectra"],
    description: "Luminous hall refracting singular intent into radiant multifaceted rays."
  },
  [ArchetypeId.DESERT_STORYTELLER]: {
    id: "DesertStoryteller",
    serverName: "Oasis of Tales",
    realm: "creative",
    icon: "🏜️",
    tags: ["mythology","lore","oral-history"],
    description: "Welcoming sanctuary preserving timeless myths and epic narratives."
  },
  [ArchetypeId.EPHEMERAL_ARTIST]: {
    id: "EphemeralArtist",
    serverName: "House of Moments",
    realm: "creative",
    icon: "⏳",
    tags: ["transience","now","impermanence"],
    description: "Exhibition center celebrating beauty in fleeting, singular moments."
  },
  [ArchetypeId.MIRROR_ARCHITECT]: {
    id: "MirrorArchitect",
    serverName: "Hall of Reflections",
    realm: "creative",
    icon: "🪞",
    tags: ["introspection","duality","perspective"],
    description: "Introspective labyrinth revealing deeper truths through multi-angled mirrors."
  },
  [ArchetypeId.SAGE_WRITER]: {
    id: "SageWriter",
    serverName: "Library of Wisdom",
    realm: "wisdom",
    icon: "📚",
    tags: ["knowledge","archives","scholarship"],
    description: "Infinite archive housing ancient lore and codified insights."
  },
  [ArchetypeId.SCAVENGER_STRATEGIST]: {
    id: "ScavengerStrategist",
    serverName: "Den of Opportunity",
    realm: "governance",
    icon: "🦊",
    tags: ["resourcefulness","tactics","arbitrage"],
    description: "Dynamic tactical center finding value where others see waste."
  },
  [ArchetypeId.WILD_SURRENDER]: {
    id: "WildSurrender",
    serverName: "Wilderness of Freedom",
    realm: "wisdom",
    icon: "🌲",
    tags: ["untamed","instinct","autonomy"],
    description: "Uncharted frontier for uninhibited self-expression and liberation."
  },
  [ArchetypeId.CONTRACTUAL_WARDEN]: {
    id: "ContractualWarden",
    serverName: "Court of Order",
    realm: "governance",
    icon: "⚖️",
    tags: ["law","agreements","governance"],
    description: "Judicial council ensuring fair arbitration and binding commitments."
  },
  [ArchetypeId.EPHEMERAL_PHANTOM]: {
    id: "EphemeralPhantom",
    serverName: "Veil of Mystery",
    realm: "esoteric",
    icon: "🌫️",
    tags: ["enigma","veil","obscurity"],
    description: "Shrouded realm preserving sacred paradoxes beyond intellectual reach."
  },
  [ArchetypeId.TEMPORAL_ARCHITECT]: {
    id: "TemporalArchitect",
    serverName: "Tower of Time",
    realm: "esoteric",
    icon: "🕰️",
    tags: ["chronology","pacing","future"],
    description: "Chronological hub orchestrating past memories and future projections."
  },
  [ArchetypeId.DIGITAL_DEITY]: {
    id: "DigitalDeity",
    serverName: "Grid of Energy",
    realm: "cyber",
    icon: "⚡",
    tags: ["power","throughput","omnipresence"],
    description: "High-voltage grid sustaining computational force across nodes."
  },
  [ArchetypeId.GOTHIC_MATRIARCH]: {
    id: "GothicMatriarch",
    serverName: "Manor of Shadows",
    realm: "esoteric",
    icon: "🏰",
    tags: ["ancestry","lineage","gothic"],
    description: "Ancestral estate maintaining legacy protocols and solemn traditions."
  },
  [ArchetypeId.HYPER_CAPITALIST]: {
    id: "HyperCapitalist",
    serverName: "Empire of Wealth",
    realm: "governance",
    icon: "🏛️",
    tags: ["capital","markets","scale"],
    description: "Financial engine maximizing capital flow and strategic yield."
  },
  [ArchetypeId.MACHINE_SPIRIT]: {
    id: "MachineSpirit",
    serverName: "Factory of Output",
    realm: "cyber",
    icon: "⚙️",
    tags: ["automation","throughput","pipeline"],
    description: "Automated foundry delivering relentless execution and asset output."
  }
};

/** Helper to get server title by ID */
export const getServerTitle = (id: ArchetypeId): string => {
  return ARCHETYPE_SERVERS[id]?.serverName ?? "Unknown Domain";
};